desc: "Xen-Troops development setup for QEMU"
min_ver: "0.27"

variables:
  YOCTOS_WORK_DIR: "yocto"
  DOM0_BUILD_DIR: "build-dom0"
  DOM0_MACHINE: "generic-armv8-xt"
  DOMD_BUILD_DIR: "build-domd"
  DOMD_MACHINE: "generic-armv8-xt"

common_data:
  # Sources used by all yocto-based domains
  sources: &COMMON_SOURCES
    - type: git
      url: "git://git.yoctoproject.org/poky"
      rev: 2f136ed7ed372a5eceb68cb6e1cdbc01c90b88d4
    - type: git
      url: "git://git.openembedded.org/meta-openembedded"
      rev: 2e3126c9c16bb3df0560f6b3896d01539a3bfad7
    - type: git
      url: "git://git.yoctoproject.org/meta-virtualization"
      rev: 6f3c1d8f90947408a6587be222fec575a1ca5195
    - type: git
      url: "https://github.com/xen-troops/meta-xt-common.git"
      rev: 0890d85d29c29265663b5e0eac7998916462c05c
    - type: git
      url: "https://github.com/dterletskiy/meta-emulator.git"
      rev: main


    # Common configuration options for all yocto-based domains
  conf: &COMMON_CONF
    - [SSTATE_DIR, "${TOPDIR}/../common_data/sstate"]
    - [DL_DIR, "${TOPDIR}/../common_data/downloads"]

components:
  dom0:
    build-dir: "%{YOCTOS_WORK_DIR}"
    default: true
    sources:
      - *COMMON_SOURCES
    builder:
      type: yocto
      work_dir: "%{DOM0_BUILD_DIR}"
      conf:
        - *COMMON_CONF
        - [MACHINE, "%{DOM0_MACHINE}"]
        - [XT_DOM_NAME, "dom0"]
        # - [XT_DOMD_CONFIG_NAME, "%{XT_DOMD_CONFIG_NAME}"]
        # - [XT_DOMD_DTB_NAME, "%{XT_DOMD_DTB_NAME}"]
        # - [XT_GUEST_INSTALL, "domd"]

        - [DISTRO_FEATURES:append, " xen"]
        - [DISTRO_FEATURES:remove, "acl alsa argp pcmcia usbgadget usbhost opengl
                                    ptest multiarch wayland vulkan sysvinit x11
                                    gtk gobject-introspection-data wifi nfc
                                    bluetooth irda zeroconf 3g"]

        # Disable HWDB which quite huge (around 15MB) and is not required at all
        - [BAD_RECOMMENDATIONS:append, " udev-hwdb"]

        - [BUILD_REPRODUCIBLE_BINARIES, "1"]

        # Enable systemd
        - [INIT_MANAGER, "systemd"]

        # Do not install kernel image to rootfs to decrease initrd size
        - ["RDEPENDS_${KERNEL_PACKAGE_NAME}-base", ""]

        # Build our own Xen version rather than proposed by meta-virtualization
        - [PREFERRED_VERSION_xen, "4.19.0+stable%"]
        - [PREFERRED_VERSION_xen-tools, "4.19.0+stable%"]

        - [BBMASK:append, " meta-xt-common/meta-xt-control-domain/recipes-guest/domd"]
        - [BBMASK:append, " meta-xt-common/meta-xt-control-domain/recipes-guest/domu"]

      layers:
        - "../poky/meta"
        - "../poky/meta-poky"
        - "../poky/meta-yocto-bsp"
        - "../meta-openembedded/meta-oe"
        - "../meta-openembedded/meta-filesystems"
        - "../meta-openembedded/meta-python"
        - "../meta-openembedded/meta-networking"
        - "../meta-virtualization"
        - "../meta-xt-common/meta-xt-domx"
        - "../meta-xt-common/meta-xt-dom0"
        - "../meta-xt-common/meta-xt-control-domain"
        - "../../layers/meta-xt-domx-qemu"
        - "../../layers/meta-xt-dom0-qemu"
      build_target: core-image-thin-initramfs
      # external_src:
      #   domd: "%{YOCTOS_WORK_DIR}/%{DOMD_BUILD_DIR}/tmp/deploy/images/%{MACHINE}/"
      # additional_deps:
      #   - "%{DOMD_BUILD_DIR}/tmp/deploy/images/%{MACHINE}/Image"
      target_images:
        - "tmp/deploy/images/%{DOM0_MACHINE}/Image"
        - "tmp/deploy/images/%{DOM0_MACHINE}/uInitramfs"

  domd:
    build-dir: "%{YOCTOS_WORK_DIR}"
    sources:
      - *COMMON_SOURCES
    builder:
      type: yocto
      work_dir: "%{DOM0_BUILD_DIR}"
      conf:
        - *COMMON_CONF
        - [MACHINE, "%{DOMD_MACHINE}"]
        - [XT_DOM_NAME, "domd"]

        - [DISTRO_FEATURES:append, " xen"]
        - [DISTRO_FEATURES:remove, "acl alsa argp pcmcia usbgadget usbhost opengl
                                    ptest multiarch wayland vulkan sysvinit x11
                                    gtk gobject-introspection-data wifi nfc
                                    bluetooth irda zeroconf 3g"]

        # Disable HWDB which quite huge (around 15MB) and is not required at all
        - [BAD_RECOMMENDATIONS:append, " udev-hwdb"]

        - [BUILD_REPRODUCIBLE_BINARIES, "1"]

        # Enable systemd
        - [INIT_MANAGER, "systemd"]

        # Do not install kernel image to rootfs to decrease initrd size
        - ["RDEPENDS_${KERNEL_PACKAGE_NAME}-base", ""]

        # Build our own Xen version rather than proposed by meta-virtualization
        - [PREFERRED_VERSION_xen, "4.19.0+stable%"]
        - [PREFERRED_VERSION_xen-tools, "4.19.0+stable%"]

      layers:
        - "../poky/meta"
        - "../poky/meta-poky"
        - "../poky/meta-yocto-bsp"
        - "../meta-openembedded/meta-oe"
        - "../meta-openembedded/meta-filesystems"
        - "../meta-openembedded/meta-python"
        - "../meta-openembedded/meta-networking"
        - "../meta-virtualization"
        - "../meta-xt-common/meta-xt-domx"
        - "../../layers/meta-xt-domx-qemu"
        - "../../layers/meta-xt-domd-qemu"
      build_target: core-image-thin-initramfs
      target_images:
        - "tmp/deploy/images/%{DOMD_MACHINE}/Image"
